baseurl = "http://schwid.com/" # Hostname (and path) to the root.
title = "Alex Shvid" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.
googleAnalytics = "UA-135001306-1"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "alexshvid" # Enable or disable Disqus.

[params] # theme parameters
    author = "Alex Shvid" # Author's name.
    info = "Deep Learning Engineer" # Author's job title or info.
    description = "Alex Shvid's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/alexshvid.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Medium"
    weight = 1
    url = "https://medium.com/@alexshvid"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/AlexShvid/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/shvid/"
[[params.social]]
    name = "Github"
    weight = 5
    url = "https://github.com/alexshvid/"

# Menu links
[[menu.main]]
    name = "Code"
    weight = 1
    url  = "posts"
#[[menu.main]]
#    name = "Projects"
#    weight = 2
#    url  = "projects"
[[menu.main]]
    name = "Resume"
    weight = 3
    url = "resume"
[[menu.main]]
    name = "Coursera"
    weight = 4
    url = "https://www.coursera.org/user/31898fcfbc971277ff1bf1ffea5bb619"
